version: '3.8'

services:
  # Kedro Viz - Visualización del pipeline
  kedro-viz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxi_ml_viz
    ports:
      - "4141:4141"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./conf:/app/conf
      - ./src:/app/src
    environment:
      - KEDRO_ENV=local
      - PYTHONPATH=/app/src
    networks:
      - taxi_network
    restart: unless-stopped
    command: ["kedro", "viz", "--host=0.0.0.0", "--port=4141", "--no-browser"]
    depends_on:
      - taxi-ml

  # Jupyter Lab - Desarrollo y análisis
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxi_ml_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - jupyter_data:/home/airlines_user/.jupyter
    environment:
      - KEDRO_ENV=local
      - PYTHONPATH=/app/src
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - taxi_network
    restart: unless-stopped
    command: ["bash", "-c", "pip install jupyter kedro[jupyter] && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"]

volumes:
  models_volume:
    driver: local
  jupyter_data:
    driver: local
  dev_cache:
    driver: local

networks:
  taxi_network:
    driver: bridge